from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
from typing import List, Dict
import os


def generate_safety_report(
    image_path: str,
    detections: List[Dict],
    summary: Dict,
    recommendations: List[str],
    output_path: str = "safety_report.pdf"
) -> str:
    """
    Generate comprehensive PDF safety report.
    
    Args:
        image_path: Path to annotated image
        detections: List of detection dictionaries
        summary: Compliance summary
        recommendations: List of AI-generated recommendations
        output_path: Path for output PDF
        
    Returns:
        Path to generated PDF
    """
    # Create PDF document
    doc = SimpleDocTemplate(output_path, pagesize=letter)
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1f77b4'),
        spaceAfter=30,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#2ca02c'),
        spaceAfter=12,
        spaceBefore=12
    )
    
    # Title
    title = Paragraph("SafetyVision AI - PPE Compliance Report", title_style)
    story.append(title)
    story.append(Spacer(1, 0.2*inch))
    
    # Timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    timestamp_para = Paragraph(f"<b>Generated:</b> {timestamp}", styles['Normal'])
    story.append(timestamp_para)
    story.append(Spacer(1, 0.3*inch))
    
    # Compliance Status
    status_heading = Paragraph("Compliance Status", heading_style)
    story.append(status_heading)
    
    status_data = [
        ['Metric', 'Value'],
        ['Status', summary['status']],
        ['Total People Detected', str(summary['total_people'])],
        ['Compliant', str(summary['compliant'])],
        ['Violations', str(summary['violations'])],
        ['Compliance Rate', f"{summary['compliance_rate']:.1f}%"]
    ]
    
    status_table = Table(status_data, colWidths=[3*inch, 3*inch])
    status_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    
    story.append(status_table)
    story.append(Spacer(1, 0.3*inch))
    
    # Annotated Image
    image_heading = Paragraph("Annotated Image", heading_style)
    story.append(image_heading)
    
    # Add image (resize to fit page)
    img = RLImage(image_path, width=5*inch, height=4*inch)
    story.append(img)
    story.append(Spacer(1, 0.3*inch))
    
    # AI Recommendations
    if recommendations:
        rec_heading = Paragraph("AI-Generated Safety Recommendations", heading_style)
        story.append(rec_heading)
        
        for i, rec in enumerate(recommendations, 1):
            rec_text = f"<b>{i}.</b> {rec}"
            rec_para = Paragraph(rec_text, styles['Normal'])
            story.append(rec_para)
            story.append(Spacer(1, 0.1*inch))
    
    story.append(Spacer(1, 0.3*inch))
    
    # Footer
    footer_text = "Generated by SafetyVision AI | PPE Compliance Monitoring System"
    footer_para = Paragraph(footer_text, styles['Normal'])
    story.append(footer_para)
    
    # Build PDF
    doc.build(story)
    print(f"PDF report generated: {output_path}")
    
    return output_path


if __name__ == "__main__":
    # Test data
    test_summary = {
        'total_people': 3,
        'compliant': 1,
        'violations': 2,
        'compliance_rate': 33.3,
        'status': 'VIOLATION DETECTED'
    }
    
    test_recommendations = [
        "Deploy additional hard hat signage at site entry points",
        "Conduct mandatory safety briefing focusing on head protection",
        "Implement spot checks during shift changes"
    ]
    
    print("PDF generator module loaded successfully!")
    print("Test data ready for PDF generation")